version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      - dependency-name: "actions/setup-node"
      - dependency-name: "actions/checkout"
      - dependency-name: "actions/upload-artifact"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      # For now, we don't want to update fumadocs, it requires tailwind 4
      - dependency-name: "fumadocs-*"
    groups:
      trpc:
        patterns:
          - "@trpc/*"
      nestjs:
        patterns:
          - "@nestjs/*"
      radix-ui:
        patterns:
          - "@radix-ui/*"
          - "radix-ui"
      drizzle:
        # drizzle-kit and drizzle-orm
        patterns:
          - "drizzle-kit"
          - "drizzle-orm"
      eslint:
        patterns:
          - "@eslint/*"
          - "eslint"
          - "typescript-eslint"
          - "eslint-plugin-*"
          - "eslint-config-*"
          - "typescript-eslint"
      fumadocs:
        patterns:
          - "fumadocs-*"
      testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "jest-*"
          - "ts-jest"
          - "@testing-library/*"
