version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      prefix-development: "deps"
      include: "scope"
    groups:
      trpc:
        patterns:
          - "@trpc/*"
      nestjs:
        patterns:
          - "@nestjs/*"
      radix-ui:
        patterns:
          - "@radix-ui/*"
      drizzle:
        # drizzle-kit and drizzle-orm
        patterns:
          - "drizzle-kit"
          - "drizzle-orm"
      eslint:
        patterns:
          - "@eslint/*"
          - "eslint"
          - "typescript-eslint"
          - "eslint-plugin-*"
      fumadocs:
        patterns:
          - "fumadocs-*"
