version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    ignore:
      - dependency-name: "actions/setup-node"
      - dependency-name: "actions/checkout"
      - dependency-name: "actions/upload-artifact"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    groups:
      trpc:
        patterns:
          - "@trpc/*"
      nestjs:
        patterns:
          - "@nestjs/*"
      radix-ui:
        patterns:
          - "@radix-ui/*"
          - "radix-ui"
      drizzle:
        # drizzle-kit and drizzle-orm
        patterns:
          - "drizzle-kit"
          - "drizzle-orm"
      eslint:
        patterns:
          - "@eslint/*"
          - "eslint"
          - "typescript-eslint"
          - "eslint-plugin-*"
          - "eslint-config-*"
          - "typescript-eslint"
      testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "jest-*"
          - "ts-jest"
          - "@testing-library/*"
          - "supertest"
      ai-sdk:
        patterns:
          - "ai"
          - "@ai-sdk/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      next:
        patterns:
          - "next"
          - "@next/*"
      t3-oss:
        patterns:
          - "@t3-oss/*"
      tambo-ai:
        patterns:
          - "@tambo-ai/*"
      small-safe-packages:
        # These aren't related, but these are all generally safe to update
        # unconditionally, so we lump them together to get one PR
        patterns:
          - "posthog-js"
          - "@splinetool/runtime"
          - "prettier"
          - "lint-staged"
          - "globals"
          - "lucide-react"
          - "@opentelemetry/*"
      sentry:
        patterns:
          - "@sentry/*"
          - sentry-*
      ag-ui:
        patterns:
          - "@ag-ui/*"
