version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      trpc:
        patterns:
          - "@trpc/*"
      nestjs:
        patterns:
          - "@nestjs/*"
      radix-ui:
        patterns:
          - "@radix-ui/*"
