// Note that this file was generated by pasting in a bunch of sample values into Cursor
// and then asking it to generate the types.

/** possible authentication modes
 * @deprecated Not used anymore
 */
export enum DeprecatedComposioAuthMode {
  API_KEY = "API_KEY",
  OAUTH2 = "OAUTH2",
  BEARER_TOKEN = "BEARER_TOKEN",
  BASIC = "BASIC",
  BASIC_WITH_JWT = "BASIC_WITH_JWT",
}
