export interface ComponentDecision {
  componentName: string | null;
  props: any | null;
  message: string;
  suggestedActions?: SuggestedAction[];
  toolCallRequest?: ToolCallRequest;
  threadId: string;
  /**
   * Flag to control whether suggestedActions should be generated.
   * When false, no suggestedActions will be generated by the AI.
   * @default true
   */
  generateSuggestedActions?: boolean;
}

export interface ComponentDecisionV2 {
  componentName: string | null;
  props: any | null;
  message: string;
}

export interface ToolCallRequest {
  toolName: string;
  parameters: {
    parameterName: string;
    parameterValue: any;
  }[];
}

/**
 * @deprecated Use HydraSuggestion from './threads' instead. This interface will be removed in the next major version.
 * ```
 */
export interface SuggestedAction {
  label: string;
  actionText: string;
}
