name: CI Coordinator

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  coordinator:
    name: CI Coordinator
    runs-on: ubuntu-latest
    needs: [build, test, lint-check]
    steps:
      - name: CI Coordination
        run: |
          echo "All CI checks have completed successfully."
  
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  lint-check:
    uses: ./.github/workflows/lint-check.yml
