name: CI Coordinator

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  coordinator:
    name: CI Status Check
    runs-on: ubuntu-latest
    # This job will run after all other workflows have completed
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Wait for other workflows
        run: |
          echo "This job coordinates the status of parallel CI workflows"
          echo "The following workflows are running in parallel:"
          echo "- Build: runs 'npm run build'"
          echo "- Test: runs 'npm run test'"
          echo "- Lint & Type Check: runs prettier, lint, and type checking"
          echo ""
          echo "These workflows run independently to improve CI performance."
