name: Deploy Database Migrations

on:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-migrations:
    name: Deploy Database Migrations
    # Skip if the actor is dependabot
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run database migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run db:migrate
        working-directory: packages/db
