name: Build and Push MCP Everything Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'apps/mcp-everything/**'
      - '.github/workflows/mcp-everything-docker.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'apps/mcp-everything/**'
      - '.github/workflows/mcp-everything-docker.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Build and Push MCP Everything Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine if we should push to GHCR
        id: should_push
        run: |
          # Push to GHCR on main branch or manual trigger
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "should_push=true" >> $GITHUB_OUTPUT
            echo "Pushing to GHCR"
          else
            echo "should_push=false" >> $GITHUB_OUTPUT
            echo "Building locally for testing (no GHCR push)"
          fi

      - name: Login to GitHub Container Registry
        if: steps.should_push.outputs.should_push == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: tambo-bot
          password: ${{ secrets.RELEASE_PACKAGES }}

      - name: Build and push mcp-everything image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/mcp-everything/Dockerfile
          push: ${{ steps.should_push.outputs.should_push }}
          load: ${{ steps.should_push.outputs.should_push == 'false' }}
          platforms: ${{ steps.should_push.outputs.should_push == 'true' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          tags: |
            ghcr.io/tambo-ai/mcp-everything:latest
            ghcr.io/tambo-ai/mcp-everything:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image built successfully
        run: |
          echo "✅ MCP Everything image built successfully"
          if [[ "${{ steps.should_push.outputs.should_push }}" == "true" ]]; then
            echo "📦 Pushed to ghcr.io/tambo-ai/mcp-everything:latest"
            echo "📦 Pushed to ghcr.io/tambo-ai/mcp-everything:${{ github.sha }}"
          else
            echo "🏗️  Built locally for testing"
          fi
