name: Tests

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "dummy-anon-key"
      NEXT_PUBLIC_SUPABASE_URL: "https://dummy-project.supabase.co"
      DATABASE_URL: "postgresql://dummy-user:dummy-password@dummy-host:5432/dummy-database"
      API_KEY_SECRET: "dummy-api-key-secret"
      PROVIDER_KEY_SECRET: "dummy-provider-key-secret"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
